### PR TITLE
Do not run tasks as root

### PR DESCRIPTION
**Pull request by ajrgrubbs**
Security 101: Never run as root unless absolutely necessary. If the process became hijacked by some vulnerability (for example, a hacker knows that by sending specially crafted data, arbitrary python can be run), correct OS permissions are a last line of defense.

This PR refactors the daemontools role so all processes are run by a "daemontools" user, which does not have sudo rights.

### CODE REVIEW

**Comment by heronblade** [comment]
@ajrgrubbs how can i test this, the changes look good, just want to be able to double check

**Comment by ajrgrubbs** [comment]
You can use one of the vagrant machines in 5c_playbooks, such as syslog. Then SSH into the VM and check what processes are running with `ps aux | grep python`. There should be processes marked as running with the daemontools user, not root.

**Comment by heronblade** [comment]
I tried `elasticsearch` `kibana` `logstash` and none of them had the process marked as running with daemontools

**Comment by ajrgrubbs** [comment]
Those machines won't work, actually. Ones like amp4e, esa, ise will. The syslog machine I mentioned would only be on the kafka-input branch of 5c_playbooks - I apologize for forgetting that.

**Comment by heronblade** [comment]
Tried it on the `esa` and `amp4e` vagrant machines, and got

```
fatal: [default]: FAILED! => {"changed": false, "cmd": "/usr/bin/git clone --origin origin '' /etc/service/esa/esa", "failed": true, "msg": "Cloning into '/etc/service/esa/esa'...\nWarning: Permanently added the RSA host key for IP address '192.30.253.112' to the list of known hosts.\r\nPermission denied (publickey).\r\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.", "rc": 128, "stderr": "Cloning into '/etc/service/esa/esa'...\nWarning: Permanently added the RSA host key for IP address '192.30.253.112' to the list of known hosts.\r\nPermission denied (publickey).\r\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\n", "stdout": "", "stdout_lines": []}

```

**Comment by ajrgrubbs** [comment]
That looks like an ssh agent forwarding issue. Have you set that up? Any ansible role that pulls down our private repos requires it.

https://developer.github.com/guides/using-ssh-agent-forwarding/

**Comment by heronblade** [comment]
i swear i've set that up so many times, looks like it wasn't i'm retrying now

**Comment by heronblade** [comment]
finally got it working `ps aux` is showing something running with `daemon`. if that's good with you then 👍

**Pull request merged**
